# Generated by Django 5.2 on 2025-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0002_management_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='銘柄コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('date', models.DateField(verbose_name='フラグ日付')),
                ('best_params', models.JSONField(verbose_name='最適値')),
                ('strategy', models.CharField(max_length=50, verbose_name='戦略名')),
                ('signal', models.CharField(max_length=10, verbose_name='シグナル')),
            ],
        ),
    ]
