# Generated by Django 5.2 on 2025-05-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0003_signalresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='銘柄コード')),
                ('strategy_name', models.CharField(max_length=50, verbose_name='戦略名')),
                ('best_params', models.JSONField(verbose_name='最適値')),
                ('final_result', models.JSONField(verbose_name='最終結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
