# Generated by Django 5.2 on 2025-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_app', '0004_optimizationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresult',
            name='interval',
            field=models.CharField(choices=[('daily', '日足'), ('minute', '5分足')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='optimizationresult',
            name='best_params',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='optimizationresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='optimizationresult',
            name='final_result',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='optimizationresult',
            name='strategy_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='optimizationresult',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
